#!/bin/bash
sudo yum install epel-release -y
sudo yum update -y 
sudo yum install yum-cron -y
curl https://raw.githubusercontent.com/diggytec/centos-utilities/master/yum-cron.conf -o yum-cron.conf
sudo cp -p yum-cron.conf /etc/yum/
sudo yum install nginx -y                                                
sudo systemctl enable nginx                                              
sudo systemctl start nginx                                               
systemctl status nginx
sudo curl https://raw.githubusercontent.com/diggytec/centos-utilities/master/mariadb.repo -o /etc/yum.repos.d/mariadb.repo
sudo yum install MariaDB-server MariaDB-client -y                                       
sudo systemctl enable mariadb                                            
sudo systemctl start mariadb                                             
sudo mysql_secure_installation                                       
sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y                                                                        
sudo yum install yum-utils -y                                            
sudo yum-config-manager --enable remi-php73                              
sudo yum install php-fpm php-mysql php-cli php-mbstring php-opcache php-curl php-gd -y                                                            
systemctl status php-fpm                                                 
sudo mkdir -p /var/www/html/example.com                 
